name: Delete Old Prereleases

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  cleanup-prereleases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but last 2 prereleases
        uses: jay2610/delete-older-releases@1.0.0
        with:
          repo: ${{ github.repository }}
          keep_latest: 2
          delete_type: "prerelease"
          delete_tag_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
